name: My New Jekyll Site
description: Blogging about stuff
meta_description: "My New Jekyll Site, Blogging about stuff"

markdown: kramdown
remote_theme: rosario/kasper
highlighter: rouge
logo: false
paginate: 15
baseurl: "craions.github.io"
domain_name: "https://craions.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Your Name"

# Disqus config
disqus-shortname: ""
